# Generated by Django 6.0.2 on 2026-02-17 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Date of the booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='management.resource'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(help_text='Time slot (e.g., 09:00-10:00)', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='management.campususer'),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='email',
            field=models.EmailField(help_text='Unique email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='name',
            field=models.CharField(help_text='Full name of the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], help_text='User role (Student/Staff)', max_length=10),
        ),
        migrations.AlterField(
            model_name='campususer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Account status', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum occupancy'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(help_text='Resource name (e.g., Computer Lab A)', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(default='AVAILABLE', help_text='Current availability status', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(help_text='Type of resource (e.g., Lab, Classroom)', max_length=100),
        ),
    ]
