# Generated by Django 6.0.2 on 2026-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_booking_booking_date_alter_booking_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='password',
            field=models.CharField(default='password123', help_text='Hashed password for login', max_length=128),
        ),
    ]
