# Generated by Django 6.0.2 on 2026-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_campususer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='campus_id',
            field=models.CharField(blank=True, help_text='Student or Staff ID', max_length=50, null=True, unique=True),
        ),
    ]
